export const SIGN_IN_ADMIN = "SIGN_IN_ADMIN";
export const SIGN_IN_ADMIN_SUCCESS = "SIGN_IN_ADMIN_SUCCESS";
export const SIGN_IN_ADMIN_FAIL = "SIGN_IN_ADMIN_FAIL";
export const SIGN_OUT_ADMIN = "SIGN_OUT_ADMIN";
