export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_BY_BLOGID = "DELETE_COMMENT_BY_BLOGID";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_BY_BLOGID_SUCCESS =
  "DELETE_COMMENT_BY_BLOGID_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_BY_BLOGID_FAIL = "DELETE_COMMENT_BY_BLOGID_FAIL";
