export const SIGN_IN_ADMIN = "SIGN_IN_ADMIN";
export const SIGN_IN_ADMIN_SUCCESS = "SIGN_IN_ADMIN_SUCCESS";
export const SIGN_IN_ADMIN_FAIL = "SIGN_IN_ADMIN_FAIL";
export const SIGN_OUT_ADMIN = "SIGN_OUT_ADMIN";

export const GET_BLOGS = "GET_BLOGS";
export const GET_BLOG = "GET_BLOG";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";

export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
